-- create DB
create table Person(

                       id int generated by default as identity primary key,
                       name varchar not null ,
                       phoneNumber varchar(11) not null,
                       date timestamp without time zone
);
drop table Person;
